
version: 2

models:
  - name: actors
    description: "List of all actors"
    columns:
      - name: actor_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: films
    description: "List of films for each actor"
    columns:
      - name: actor_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
